mod balancer_v2;
mod balancer_v3;
mod bebop;
mod curve;
mod ekubo;
mod ekubo_v3;
mod erc_4626;
mod etherfi;
mod fluid_v1;
mod hashflow;
mod maverick_v2;
mod rocketpool;
mod slipstreams;
pub mod swap_encoder_registry;
mod uniswap_v2;
mod uniswap_v3;
mod uniswap_v4;
mod weth;
