[package]
name = "tycho-indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tycho-indexer"
path = "src/main.rs"

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1.73"
futures03 = { version = "0.3.1", package = "futures", features = ["compat"] }
hex = "0.4.3"
reqwest = "0.11"
tokio = { version = "1.27", features = [
    "time",
    "sync",
    "macros",
    "test-util",
    "rt-multi-thread",
    "parking_lot",
] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-retry = "0.3"
tonic = { version = "0.9", features = ["tls-roots"] }
prost = "0.11"
prost-types = "0.11"
thiserror = "1"
diesel = { version = "2.1.0", features = ["postgres", "chrono", "serde_json"] }
diesel-derive-enum = { version = "2.1.0", features = ["postgres"] }
diesel_migrations = "2.1.0"
diesel-async = { version = "0.3.1", features = ["postgres", "bb8"] }
serde_json = "1.0.105"
chrono = { version = "0.4.26", features = ["serde"] }
ethers = "^2.0.2"
serde = "1.0"
clap = { version = "4.4.2", features = ["derive", "env"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", default-features = false, features = [
    "env-filter",
    "fmt",
] }
once_cell = "1.18.0"
actix = "0.13.1"
actix-web = "4.4.0"
actix-web-actors = "4.2.0"
tracing-actix-web = "0.7.6"
uuid = { version = "1.4.1", features = [
    "serde",
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }

[dev-dependencies]
actix-rt = "2.9.0"
actix-test = "0.1.2"
rstest = "0.18.2"
tokio-tungstenite = "0.20.0"
