server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://lgtm:3100/loki/api/v1/push

scrape_configs:
  # Only collect logs from tycho-indexer service
  - job_name: tycho-indexer
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["service=tycho-indexer"]

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      
      # Parse structured Rust logs
      - regex:
          source: output
          expression: '^\s*(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})?)\s+(?P<level>\w+)\s+(?P<target>[^:]+):?\s*(?P<message>.*)'
      
      # Extract tracing spans and fields  
      - regex:
          source: message
          expression: '(?P<span_name>\w+)(?:\{[^}]*\})?: (?P<span_message>.*)'

      - labels:
          level:
          target:
          container_name:
          stream:
          span_name:
          service: tycho-indexer

      # Set output to the cleaned message
      - output:
          source: message