// @generated
// This file is @generated by prost-build.
/// Copy of tycho.evm.v1.Transaction to be able to implement conversions to/from
/// TransactionTrace
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub index: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TickDelta {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag="2")]
    pub tick_index: i32,
    /// int128
    #[prost(bytes="vec", tag="3")]
    pub liquidity_net_delta: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="4")]
    pub ordinal: u64,
    #[prost(message, optional, tag="5")]
    pub transaction: ::core::option::Option<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TickDeltas {
    #[prost(message, repeated, tag="1")]
    pub deltas: ::prost::alloc::vec::Vec<TickDelta>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateDelta {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub time: u64,
    /// int112
    #[prost(bytes="vec", tag="3")]
    pub rate_delta: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="4")]
    pub is_token1: bool,
    #[prost(uint64, tag="5")]
    pub ordinal: u64,
    #[prost(message, optional, tag="6")]
    pub transaction: ::core::option::Option<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateDeltas {
    #[prost(message, repeated, tag="1")]
    pub deltas: ::prost::alloc::vec::Vec<RateDelta>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveLiquidityChange {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    /// uint128 or int128, depending on change_type
    #[prost(bytes="vec", tag="2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration="ChangeType", tag="3")]
    pub change_type: i32,
    #[prost(uint64, tag="4")]
    pub ordinal: u64,
    #[prost(message, optional, tag="5")]
    pub transaction: ::core::option::Option<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveLiquidityChanges {
    #[prost(message, repeated, tag="1")]
    pub changes: ::prost::alloc::vec::Vec<ActiveLiquidityChange>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveRateChange {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    /// uint112 or int112, depending on change_type
    #[prost(bytes="vec", tag="2")]
    pub token0_value: ::prost::alloc::vec::Vec<u8>,
    /// uint112 or int112, depending on change_type
    #[prost(bytes="vec", tag="3")]
    pub token1_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration="ChangeType", tag="4")]
    pub change_type: i32,
    #[prost(uint64, tag="5")]
    pub ordinal: u64,
    #[prost(message, optional, tag="6")]
    pub transaction: ::core::option::Option<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActiveRateChanges {
    #[prost(message, repeated, tag="1")]
    pub changes: ::prost::alloc::vec::Vec<ActiveRateChange>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolDetails {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub token0: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="3")]
    pub is_stableswap: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockTransactionEvents {
    #[prost(message, repeated, tag="1")]
    pub block_transaction_events: ::prost::alloc::vec::Vec<block_transaction_events::TransactionEvents>,
    /// block timestamp
    #[prost(uint64, tag="2")]
    pub timestamp: u64,
}
/// Nested message and enum types in `BlockTransactionEvents`.
pub mod block_transaction_events {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
    pub struct TransactionEvents {
        #[prost(message, optional, tag="1")]
        pub transaction: ::core::option::Option<super::Transaction>,
        #[prost(message, repeated, tag="2")]
        pub pool_logs: ::prost::alloc::vec::Vec<transaction_events::PoolLog>,
    }
    /// Nested message and enum types in `TransactionEvents`.
    pub mod transaction_events {
        #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
        pub struct PoolLog {
            #[prost(uint64, tag="1")]
            pub ordinal: u64,
            /// bytes32
            #[prost(bytes="vec", tag="2")]
            pub pool_id: ::prost::alloc::vec::Vec<u8>,
            #[prost(oneof="pool_log::Event", tags="3, 4, 5, 6, 7, 8")]
            pub event: ::core::option::Option<pool_log::Event>,
        }
        /// Nested message and enum types in `PoolLog`.
        pub mod pool_log {
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct Swapped {
                /// int128
                #[prost(bytes="vec", tag="1")]
                pub delta0: ::prost::alloc::vec::Vec<u8>,
                /// int128
                #[prost(bytes="vec", tag="2")]
                pub delta1: ::prost::alloc::vec::Vec<u8>,
                /// uint192
                #[prost(bytes="vec", tag="3")]
                pub sqrt_ratio_after: ::prost::alloc::vec::Vec<u8>,
                /// uint128
                #[prost(bytes="vec", tag="4")]
                pub liquidity_after: ::prost::alloc::vec::Vec<u8>,
                /// int32
                #[prost(sint32, tag="5")]
                pub tick_after: i32,
            }
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct PositionUpdated {
                /// int32
                #[prost(sint32, tag="1")]
                pub lower: i32,
                /// int32
                #[prost(sint32, tag="2")]
                pub upper: i32,
                /// int128
                #[prost(bytes="vec", tag="3")]
                pub liquidity_delta: ::prost::alloc::vec::Vec<u8>,
                /// int128
                #[prost(bytes="vec", tag="4")]
                pub delta0: ::prost::alloc::vec::Vec<u8>,
                /// int128
                #[prost(bytes="vec", tag="5")]
                pub delta1: ::prost::alloc::vec::Vec<u8>,
            }
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct PoolInitialized {
                /// address
                #[prost(bytes="vec", tag="1")]
                pub token0: ::prost::alloc::vec::Vec<u8>,
                /// address
                #[prost(bytes="vec", tag="2")]
                pub token1: ::prost::alloc::vec::Vec<u8>,
                /// bytes32
                #[prost(bytes="vec", tag="3")]
                pub config: ::prost::alloc::vec::Vec<u8>,
                /// int32
                #[prost(sint32, tag="4")]
                pub tick: i32,
                /// uint192
                #[prost(bytes="vec", tag="5")]
                pub sqrt_ratio: ::prost::alloc::vec::Vec<u8>,
                #[prost(bool, tag="6")]
                pub has_time_rate_deltas: bool,
            }
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct VirtualExecution {
                /// int112/uint112
                #[prost(bytes="vec", tag="1")]
                pub token0_rate: ::prost::alloc::vec::Vec<u8>,
                /// int112/uint112
                #[prost(bytes="vec", tag="2")]
                pub token1_rate: ::prost::alloc::vec::Vec<u8>,
            }
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct RateUpdated {
                /// block timestamp
                #[prost(uint64, tag="1")]
                pub start_time: u64,
                /// block timestamp
                #[prost(uint64, tag="2")]
                pub end_time: u64,
                /// int112
                #[prost(bytes="vec", tag="3")]
                pub token0_rate_delta: ::prost::alloc::vec::Vec<u8>,
                /// int112
                #[prost(bytes="vec", tag="4")]
                pub token1_rate_delta: ::prost::alloc::vec::Vec<u8>,
            }
            /// The complete state of one pool at the seed block, reconstructed by the package's seed
            /// writer (`seed/`). Emitted once per pool in the synthetic seed transaction; every store
            /// module rebuilds its entry for the pool from this single event.
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct PoolSnapshot {
                /// address
                #[prost(bytes="vec", tag="1")]
                pub token0: ::prost::alloc::vec::Vec<u8>,
                /// address
                #[prost(bytes="vec", tag="2")]
                pub token1: ::prost::alloc::vec::Vec<u8>,
                /// bytes32
                #[prost(bytes="vec", tag="3")]
                pub config: ::prost::alloc::vec::Vec<u8>,
                /// int32
                #[prost(sint32, tag="4")]
                pub tick: i32,
                /// uint192
                #[prost(bytes="vec", tag="5")]
                pub sqrt_ratio: ::prost::alloc::vec::Vec<u8>,
                /// uint128, signed big-endian like the store values it seeds
                #[prost(bytes="vec", tag="6")]
                pub liquidity: ::prost::alloc::vec::Vec<u8>,
                /// Initialized ticks with a nonzero net liquidity delta, sorted by index.
                #[prost(message, repeated, tag="7")]
                pub ticks: ::prost::alloc::vec::Vec<TickSnapshot>,
                /// int128, token0 reserves implied by the liquidity distribution
                #[prost(bytes="vec", tag="8")]
                pub balance0: ::prost::alloc::vec::Vec<u8>,
                /// int128, token1 reserves implied by the liquidity distribution
                #[prost(bytes="vec", tag="9")]
                pub balance1: ::prost::alloc::vec::Vec<u8>,
                /// Set only for pools whose extension carries time rate deltas (TWAMM, BoostedFees).
                #[prost(message, optional, tag="10")]
                pub timed: ::core::option::Option<TimedSnapshot>,
            }
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct TickSnapshot {
                /// int32
                #[prost(sint32, tag="1")]
                pub index: i32,
                /// int128
                #[prost(bytes="vec", tag="2")]
                pub liquidity_delta: ::prost::alloc::vec::Vec<u8>,
            }
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct TimedSnapshot {
                /// last virtual order execution / fee donation timestamp
                #[prost(uint64, tag="1")]
                pub last_time: u64,
                /// uint112, signed big-endian like the store values it seeds
                #[prost(bytes="vec", tag="2")]
                pub rate0: ::prost::alloc::vec::Vec<u8>,
                /// uint112, signed big-endian like the store values it seeds
                #[prost(bytes="vec", tag="3")]
                pub rate1: ::prost::alloc::vec::Vec<u8>,
                #[prost(message, repeated, tag="4")]
                pub rate_deltas: ::prost::alloc::vec::Vec<RateDeltaSnapshot>,
            }
            /// Rate deltas becoming active at `time`. An empty delta means "no delta for this token",
            /// mirroring `RateUpdated`.
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
            pub struct RateDeltaSnapshot {
                #[prost(uint64, tag="1")]
                pub time: u64,
                /// int112
                #[prost(bytes="vec", tag="2")]
                pub delta0: ::prost::alloc::vec::Vec<u8>,
                /// int112
                #[prost(bytes="vec", tag="3")]
                pub delta1: ::prost::alloc::vec::Vec<u8>,
            }
            #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
            pub enum Event {
                #[prost(message, tag="3")]
                Swapped(Swapped),
                #[prost(message, tag="4")]
                PositionUpdated(PositionUpdated),
                #[prost(message, tag="5")]
                PoolInitialized(PoolInitialized),
                #[prost(message, tag="6")]
                VirtualExecution(VirtualExecution),
                #[prost(message, tag="7")]
                RateUpdated(RateUpdated),
                #[prost(message, tag="8")]
                PoolSnapshot(PoolSnapshot),
            }
        }
    }
}
/// Body of the package's seed file: the state of every Ekubo v3 pool after the seed block. The
/// block itself is named by the seed file's header, so an empty body is a valid seed of no pools.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Seed {
    #[prost(message, repeated, tag="1")]
    pub pools: ::prost::alloc::vec::Vec<PoolSeed>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolSeed {
    /// bytes32
    #[prost(bytes="vec", tag="1")]
    pub pool_id: ::prost::alloc::vec::Vec<u8>,
    /// uint96, the packed float as stored by the core contract
    #[prost(bytes="vec", tag="2")]
    pub sqrt_ratio_float: ::prost::alloc::vec::Vec<u8>,
    /// `snapshot.sqrt_ratio` is left empty; the package fills it from `sqrt_ratio_float`.
    #[prost(message, optional, tag="3")]
    pub snapshot: ::core::option::Option<block_transaction_events::transaction_events::pool_log::PoolSnapshot>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChangeType {
    Delta = 0,
    Absolute = 1,
}
impl ChangeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ChangeType::Delta => "DELTA",
            ChangeType::Absolute => "ABSOLUTE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DELTA" => Some(Self::Delta),
            "ABSOLUTE" => Some(Self::Absolute),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
