// Generated from the `error` entries of the ABIs under abi/ plus the Solidity built-in
// `Error(string)` and `Panic(uint256)`. Regenerate with scripts/gen_error_table.py.

/// Custom error name and its parameter types, used to resolve revert selectors.
pub(crate) const ERRORS: &[(&str, &[&str])] = &[
    ("AccessControlBadConfirmation", &[]),
    ("AccessControlUnauthorizedAccount", &["address", "bytes32"]),
    ("Dispatcher__CallbackReverted", &["address"]),
    ("Dispatcher__ExecutorAlreadyExists", &["address"]),
    ("Dispatcher__ExecutorIsTimelocked", &["address"]),
    ("Dispatcher__NonContractExecutor", &[]),
    ("Dispatcher__SwapReverted", &["address"]),
    ("Dispatcher__UnapprovedExecutor", &["address"]),
    ("Dispatcher__UnsupportedSingleHopCycle", &["address"]),
    ("ECDSAInvalidSignature", &[]),
    ("ECDSAInvalidSignatureLength", &["uint256"]),
    ("ECDSAInvalidSignatureS", &["bytes32"]),
    ("ERC6909InsufficientAllowance", &["address", "uint256", "uint256", "uint256"]),
    ("ERC6909InsufficientBalance", &["address", "uint256", "uint256", "uint256"]),
    ("ERC6909InvalidApprover", &["address"]),
    ("ERC6909InvalidReceiver", &["address"]),
    ("ERC6909InvalidSender", &["address"]),
    ("ERC6909InvalidSpender", &["address"]),
    ("EnforcedPause", &[]),
    ("Error", &["string"]),
    ("ExpectedPause", &[]),
    ("FailedCall", &[]),
    ("FeeCalculator__AddressZero", &[]),
    ("FeeCalculator__FeeTooHigh", &[]),
    ("InsufficientBalance", &["uint256", "uint256"]),
    ("InvalidShortString", &[]),
    ("Panic", &["uint256"]),
    ("ReentrancyGuardReentrantCall", &[]),
    ("RestrictTransferFrom__AddressZero", &[]),
    ("SafeERC20FailedOperation", &["address"]),
    ("StringTooLong", &["string"]),
    ("TransferManager__DifferentTokenIn", &["address", "address"]),
    ("TransferManager__ExceededTransferFromAllowance", &["uint256", "uint256"]),
    ("TransferManager__NotAContract", &["address"]),
    ("TransferManager__UnknownTransferType", &[]),
    ("TychoRouter__AddressZero", &[]),
    ("TychoRouter__AmountOutNotFullyReceived", &["uint256", "uint256"]),
    ("TychoRouter__AmountOutZero", &[]),
    ("TychoRouter__EmptySwaps", &[]),
    ("TychoRouter__ExpiredClientSignature", &["uint256", "uint256"]),
    ("TychoRouter__FeesExceedOutput", &["uint256", "uint256"]),
    ("TychoRouter__InvalidClientSignature", &[]),
    ("TychoRouter__InvalidMinAmountOut", &["uint256", "uint256"]),
    ("TychoRouter__MessageValueMismatch", &["uint256", "uint256"]),
    ("TychoRouter__MsgValueDoesNotMatchAmountIn", &["uint256", "uint256"]),
    ("TychoRouter__NegativeOutputDelta", &["int256"]),
    ("TychoRouter__NegativeSlippage", &["uint256", "uint256"]),
    ("TychoRouter__NoPendingFeeCalculator", &[]),
    ("TychoRouter__NotAContract", &["address"]),
    ("TychoRouter__TimelockNotExpired", &["uint256", "uint256"]),
    ("TychoRouter__UndefinedMinAmountOut", &[]),
    ("TychoRouter__ZeroInput", &[]),
    ("Vault__AddressZero", &[]),
    ("Vault__AmountZero", &[]),
    ("Vault__InsufficientBalance", &["address", "address", "uint256", "uint256"]),
    ("Vault__UnexpectedInputDelta", &["int256"]),
    ("Vault__UnexpectedNonZeroCount", &["uint256"]),
];
