[workspace]
members = [
    "ethereum-cowamm",
    "ethereum-balancer-v2",
    "ethereum-curve",
    "crates/tycho-substreams",
    "crates/substreams-helper",
    "ethereum-ambient",
    "ethereum-uniswap-v2",
    "ethereum-uniswap-v3",
    "ethereum-pancakeswap-v3",
    "ethereum-sfrax",
    "ethereum-sfraxeth",
    "ethereum-uniswap-v3-logs-only",
    "ethereum-template-factory",
    "ethereum-template-singleton",
    "ethereum-uniswap-v4/shared",
    "ethereum-uniswap-v4/no-hooks",
    "ethereum-uniswap-v4/with-hooks",
    "ethereum-ekubo-v2",
    "ethereum-ekubo-v3",
    "ethereum-maverick-v2",
    "ethereum-lido",
    "ethereum-balancer-v3",
    "ethereum-fluid",
    "base-aerodrome-v1",
    "base-aerodrome-slipstreams",
    "base-lunarbase",
    "ethereum-erc4626",
    "ethereum-rocketpool",
    "unichain-velodrome",
    "ethereum-liquidityparty",
    "ethereum-fermiswap",
    "ethereum-bopamm",
    "ethereum-ring-swap-v2",
    "ethereum-sky",
    "polygon-ramses-v3",
    "ethereum-pendle",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
