// @generated
// This file is @generated by prost-build.
/// All router trades found in one block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trades {
    #[prost(message, repeated, tag="1")]
    pub trades: ::prost::alloc::vec::Vec<Trade>,
    #[prost(message, repeated, tag="2")]
    pub errors: ::prost::alloc::vec::Vec<RouterCallError>,
}
/// A selector-matched router call that could not be decoded safely.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RouterCallError {
    #[prost(string, tag="1")]
    pub chain: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(uint64, tag="3")]
    pub block_timestamp: u64,
    #[prost(bytes="vec", tag="4")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub tx_index: u32,
    #[prost(uint32, tag="6")]
    pub call_index: u32,
    #[prost(bytes="vec", tag="7")]
    pub router: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub router_version: ::prost::alloc::string::String,
    /// Decode stage: "calldata", "amount_out" or "hops".
    #[prost(string, tag="9")]
    pub stage: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub error: ::prost::alloc::string::String,
    #[prost(bool, tag="11")]
    pub tx_success: bool,
    #[prost(bool, tag="12")]
    pub call_success: bool,
    /// Whether the chain kept the state changes of the call. See Trade.state_committed.
    #[prost(bool, tag="13")]
    pub state_committed: bool,
}
/// One call into a TychoRouter swap entry point (successful or reverted).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Trade {
    #[prost(string, tag="1")]
    pub chain: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(uint64, tag="3")]
    pub block_timestamp: u64,
    #[prost(bytes="vec", tag="4")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub tx_index: u32,
    /// Index of the router call inside the transaction trace; unique per tx.
    #[prost(uint32, tag="6")]
    pub call_index: u32,
    /// True when the enclosing transaction succeeded.
    #[prost(bool, tag="7")]
    pub tx_success: bool,
    /// True when the router call itself did not revert or fail.
    #[prost(bool, tag="8")]
    pub call_success: bool,
    #[prost(bytes="vec", tag="9")]
    pub router: ::prost::alloc::vec::Vec<u8>,
    /// Router ABI generation: "v2", "v3_0" or "v3_1".
    #[prost(string, tag="10")]
    pub router_version: ::prost::alloc::string::String,
    /// "single", "sequential" or "split".
    #[prost(string, tag="11")]
    pub strategy: ::prost::alloc::string::String,
    /// How user funds enter the router: "transfer_from", "permit2", "vault" or "none".
    #[prost(string, tag="12")]
    pub funding: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="13")]
    pub eoa: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="14")]
    pub msg_sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="15")]
    pub receiver: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="16")]
    pub token_in: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="17")]
    pub token_out: ::prost::alloc::vec::Vec<u8>,
    /// Decimal strings; empty when not present for this router version / outcome.
    #[prost(string, tag="18")]
    pub amount_in: ::prost::alloc::string::String,
    #[prost(string, tag="19")]
    pub expected_amount_out: ::prost::alloc::string::String,
    #[prost(string, tag="20")]
    pub min_amount_out: ::prost::alloc::string::String,
    /// Settled output amount after fees, decoded from the call return value.
    #[prost(string, tag="21")]
    pub amount_out: ::prost::alloc::string::String,
    #[prost(string, tag="22")]
    pub native_value: ::prost::alloc::string::String,
    #[prost(uint64, tag="23")]
    pub gas_used: u64,
    /// Revert data: 4-byte selector (hex) and the resolved error name / reason string.
    #[prost(string, tag="24")]
    pub revert_selector: ::prost::alloc::string::String,
    #[prost(string, tag="25")]
    pub revert_reason: ::prost::alloc::string::String,
    #[prost(message, optional, tag="26")]
    pub client_fee: ::core::option::Option<ClientFee>,
    #[prost(message, optional, tag="27")]
    pub router_fee_config: ::core::option::Option<RouterFeeConfig>,
    #[prost(message, repeated, tag="28")]
    pub fees_taken: ::prost::alloc::vec::Vec<FeeTaken>,
    #[prost(uint32, tag="29")]
    pub n_tokens: u32,
    #[prost(message, repeated, tag="30")]
    pub hops: ::prost::alloc::vec::Vec<Hop>,
    /// Trailing calldata appended after the ABI-encoded arguments.
    #[prost(bytes="vec", tag="31")]
    pub watermark: ::prost::alloc::vec::Vec<u8>,
    /// V2 only.
    #[prost(bool, tag="32")]
    pub wrap_eth: bool,
    #[prost(bool, tag="33")]
    pub unwrap_eth: bool,
    /// Whether the chain kept the state changes of the call.
    ///
    /// A call can return normally and still have every state change it made thrown away, because
    /// an ancestor call reverted afterwards. A caller quoting the router on chain does exactly
    /// that: it calls the router, reads the return value, then reverts. Such a call carries
    /// tx_success and call_success like a fill, so this is the only field that separates the two.
    #[prost(bool, tag="34")]
    pub state_committed: bool,
}
/// One executor invocation inside a trade.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Hop {
    #[prost(uint32, tag="1")]
    pub index: u32,
    #[prost(bytes="vec", tag="2")]
    pub executor: ::prost::alloc::vec::Vec<u8>,
    /// Split swaps only: indices into the trade's token array and the raw uint24 split
    /// (0 means "remainder").
    #[prost(uint32, tag="4")]
    pub token_in_index: u32,
    #[prost(uint32, tag="5")]
    pub token_out_index: u32,
    #[prost(uint32, tag="6")]
    pub split: u32,
    #[prost(bytes="vec", tag="7")]
    pub protocol_data: ::prost::alloc::vec::Vec<u8>,
}
/// ClientFeeParams passed to V3 routers.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientFee {
    #[prost(uint64, tag="1")]
    pub fee_bps: u64,
    #[prost(bytes="vec", tag="2")]
    pub receiver: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub max_client_contribution: ::prost::alloc::string::String,
    /// uint256 decimal string; the encoder uses uint256 max for "no deadline".
    #[prost(string, tag="4")]
    pub deadline: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub has_signature: bool,
}
/// Router fee configuration in effect for this trade, resolved from the fee store.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RouterFeeConfig {
    #[prost(bytes="vec", tag="1")]
    pub fee_calculator: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub fee_on_output_bps: u64,
    #[prost(uint64, tag="3")]
    pub fee_on_client_fee_bps: u64,
    #[prost(bool, tag="4")]
    pub custom_fee_on_output: bool,
    #[prost(bool, tag="5")]
    pub custom_fee_on_client_fee: bool,
    #[prost(bool, tag="6")]
    pub positive_slippage_enabled: bool,
    /// Denominator of the bps values: 10000 for v3_0, 100000000 for v3_1.
    #[prost(uint64, tag="7")]
    pub bps_scale: u64,
    /// Whether this trade's client is exempt from positive slippage capture. The client is the
    /// signed clientFeeReceiver, or tx.origin when that is zero, the same resolution the
    /// FeeCalculator does. Only the calculator generation that has exemptions can set it.
    #[prost(bool, tag="8")]
    pub positive_slippage_exempt: bool,
}
/// One recipient of the FeesTaken event.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeTaken {
    #[prost(bytes="vec", tag="1")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
    /// Contract array position: "router" first, then "client".
    #[prost(string, tag="3")]
    pub role: ::prost::alloc::string::String,
    /// The credited token, from the event rather than the calldata, so a vault balance built on
    /// this does not depend on the swap decoder.
    #[prost(bytes="vec", tag="4")]
    pub token: ::prost::alloc::vec::Vec<u8>,
}
/// Fee configuration changes found in one block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeConfigEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<FeeConfigEvent>,
}
/// One admin event on a FeeCalculator or a fee-calculator rotation on a router.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeeConfigEvent {
    #[prost(string, tag="1")]
    pub chain: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(uint64, tag="3")]
    pub block_timestamp: u64,
    #[prost(bytes="vec", tag="4")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub log_index: u32,
    #[prost(uint64, tag="6")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="7")]
    pub emitter: ::prost::alloc::vec::Vec<u8>,
    /// Event name, e.g. "RouterFeeOnOutputUpdated", "FeeCalculatorActivated".
    #[prost(string, tag="8")]
    pub event: ::prost::alloc::string::String,
    /// Client address for Custom* events; empty otherwise.
    #[prost(bytes="vec", tag="9")]
    pub client: ::prost::alloc::vec::Vec<u8>,
    /// Decimal / hex string representation of the old and new values.
    #[prost(string, tag="10")]
    pub old_value: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub new_value: ::prost::alloc::string::String,
    /// Denominator of the bps values this emitter uses, when the event gives its generation away;
    /// 0 otherwise. The two FeeCalculator generations widened the bps arguments from uint16 to
    /// uint32, so an event that carries one has a different topic in each.
    #[prost(uint64, tag="12")]
    pub bps_scale: u64,
}
/// Every ERC-6909 Transfer a router emitted in one block.
///
/// The router keeps a vault of internal token balances. It credits a fee recipient there instead
/// of transferring, so router revenue accrues as a vault balance until someone withdraws it.
///
/// Fee credits are NOT in here: the router mints those without an event to save gas, and reports
/// them through FeesTaken instead (see FeeTaken). A balance therefore needs both sources.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultTransfers {
    #[prost(message, repeated, tag="1")]
    pub transfers: ::prost::alloc::vec::Vec<VaultTransfer>,
}
/// One ERC-6909 Transfer: a deposit, a withdrawal, or a move between two owners.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultTransfer {
    #[prost(string, tag="1")]
    pub chain: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub block_number: u64,
    #[prost(uint64, tag="3")]
    pub block_timestamp: u64,
    #[prost(bytes="vec", tag="4")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub log_index: u32,
    /// The router holding the vault. Each router has its own, so a balance is per router.
    #[prost(bytes="vec", tag="6")]
    pub router: ::prost::alloc::vec::Vec<u8>,
    /// msg.sender of the call that moved the balance. The owner of an operator-driven move.
    #[prost(bytes="vec", tag="7")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// Debited owner; empty on a credit (mint).
    #[prost(bytes="vec", tag="8")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    /// Credited owner; empty on a debit (burn).
    #[prost(bytes="vec", tag="9")]
    pub receiver: ::prost::alloc::vec::Vec<u8>,
    /// The ERC-6909 id, which the router derives from the token address.
    #[prost(bytes="vec", tag="10")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="11")]
    pub amount: ::prost::alloc::string::String,
    /// "credit" (minted), "debit" (burned) or "transfer" (between two owners).
    #[prost(string, tag="12")]
    pub kind: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
