name: Substreams CI

on:
  pull_request:
    paths:
      - 'protocols/substreams/**'
      - '!**/Cargo.lock'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Substreams Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
          submodules: false
          fetch-depth: 0

      - name: Check if any Substreams files changed
        id: substreams-files-changed
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c  # v45
        with:
          files: protocols/substreams/**

      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9  # nightly
        if: steps.substreams-files-changed.outputs.any_changed == 'true'
        with:
          toolchain: nightly
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6  # v2.7.8
        if: steps.substreams-files-changed.outputs.any_changed == 'true'
        with:
          cache-on-failure: true

      - name: Get changed Substreams package names
        if: steps.substreams-files-changed.outputs.any_changed == 'true'
        id: changed_packages
        uses: ./.github/actions/substreams-check
        with:
          changed-files: ${{ steps.substreams-files-changed.outputs.all_changed_files }}

      - name: Run checks
        if: steps.substreams-files-changed.outputs.any_changed == 'true'
        shell: bash
        run: |
          cd protocols/substreams
          if [ -n "${{ steps.changed_packages.outputs.package_names }}" ]; then
            for package in ${{ steps.changed_packages.outputs.package_names }}; do
              echo "Running checks for package: $package"
              cargo +nightly fmt --package "$package" -- --check
              cargo +nightly clippy --package "$package" -- -D warnings
            done
          else
            echo "No packages to check"
          fi

      - name: Skip check
        if: steps.substreams-files-changed.outputs.any_changed != 'true'
        run: echo "No changes to substreams directory, skipping lint check"

  test:
    name: Substreams Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
          submodules: false
          fetch-depth: 0

      - name: Check if any Substreams files changed
        id: substreams-files-changed
        uses: tj-actions/changed-files@48d8f15b2aaa3d255ca5af3eba4870f807ce6b3c  # v45
        with:
          files: protocols/substreams/**

      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1  # stable
        if: steps.substreams-files-changed.outputs.any_changed == 'true'
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6  # v2.7.8
        if: steps.substreams-files-changed.outputs.any_changed == 'true'
        with:
          cache-on-failure: true

      - name: Get changed Substreams package names
        if: steps.substreams-files-changed.outputs.any_changed == 'true'
        id: changed_packages
        uses: ./.github/actions/substreams-check
        with:
          changed-files: ${{ steps.substreams-files-changed.outputs.all_changed_files }}

      - name: Run tests
        if: steps.substreams-files-changed.outputs.any_changed == 'true'
        shell: bash
        run: |
          cd protocols/substreams
          if [ -n "${{ steps.changed_packages.outputs.package_names }}" ]; then
            for package in ${{ steps.changed_packages.outputs.package_names }}; do
              echo "Running tests for package: $package"
              cargo build --package "$package" --target wasm32-unknown-unknown
              cargo test --package "$package"
            done
          else
            echo "No packages to test"
          fi

      - name: Skip check
        if: steps.substreams-files-changed.outputs.any_changed != 'true'
        run: echo "No changes to substreams directory, skipping test check"
