name: Release

on:
  workflow_dispatch:
    inputs: { }
  release:
    types: [ created, prereleased ]

permissions:
  id-token: write
  contents: write

jobs:
  upload-assets:
    strategy:
      matrix:
        include:
          - package: tycho-client
            target: aarch64-apple-darwin
            os: macos-latest
          - package: tycho-client
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - package: tycho-client
            target: x86_64-apple-darwin
            os: macos-latest
          - package: tycho-indexer
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Install PostgreSQL Client on macOS
        if: runner.os == 'macOS'
        run: |
          brew install libpq
          brew link --force libpq
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.package }}
          archive: ${{ matrix.package }}-${{ matrix.target }}-${{ github.event.release.tag_name }}
          target: ${{ matrix.target }}
          tar: all
          zip: none
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload binary to S3
        run: |
          FILE_NAME=${{ matrix.package }}-${{ matrix.target }}-${{ github.event.release.tag_name }}.tar.gz
          BUCKET_NAME=repo.propellerheads-propellerheads/tycho-client
          aws s3 cp $FILE_NAME s3://$BUCKET_NAME/$FILE_NAME
  publish-crate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Push to crates.io
        run: |
          cargo publish --locked --verbose --token ${{ secrets.CRATESIO_REGISTRY_TOKEN }} --package tycho-common
          cargo publish --locked --verbose --token ${{ secrets.CRATESIO_REGISTRY_TOKEN }} --package tycho-client
# we can't use the action because it errors on github dependencies in any workspace crate
#      - uses: katyo/publish-crates@v2
#        with:
#          path: "./tycho-common"
#          registry-token: ${{ secrets.CRATESIO_REGISTRY_TOKEN }}

