name: Release Substreams

on:
  push:
    tags:
      - 'substreams/v*'
  workflow_dispatch:
    inputs:
      package:
        required: true
        description: "Package to build and release"
      config_file:
        required: false
        description: "Name of the substreams configuration file"
        default: "substreams"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crates:
    name: Publish substreams crates to crates.io
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
          submodules: false

      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1  # stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6  # v2.7.8
        with:
          cache-on-failure: true

      - name: Publish substreams-helper
        working-directory: substreams
        run: cargo publish -p substreams-helper --locked --token ${{ secrets.CRATESIO_REGISTRY_TOKEN }}

      - name: Wait for crates.io to index substreams-helper
        run: sleep 30

      - name: Publish tycho-substreams
        working-directory: substreams
        run: cargo publish -p tycho-substreams --locked --token ${{ secrets.CRATESIO_REGISTRY_TOKEN }}

  release-substreams-package:
    name: Release ${{ inputs.package }} substreams package
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
          submodules: false

      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1  # stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6  # v2.7.8
        with:
          cache-on-failure: true

      - name: Install Substreams CLI
        run: |
          LINK=$(curl -s https://api.github.com/repos/streamingfast/substreams/releases/latest \
            | awk "/download.url.*linux_$(uname -m)/ {print \$2}" | sed 's/"//g')
          curl -L "$LINK" | tar zxf - -C /usr/local/bin
          chmod +x /usr/local/bin/substreams
          substreams --version

      - name: Build and release substreams package
        working-directory: substreams
        run: ./release.sh ${{ inputs.package }} ${{ inputs.config_file }}
